drop table if exists users, orders_items, orders, items;

create table users
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login            varchar(100),
    password         varchar(100),
    role             varchar(50),
    number_phone     varchar(50) UNIQUE,
    address          varchar(150),
    telegram_user_id   int,
    can_create_order boolean,
    dtype            varchar(100)
);

create table orders
(
    id_order      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_customer   int REFERENCES users (id) on DELETE CASCADE,
    id_specialist int REFERENCES users (id) on DELETE SET NULL,
    status_order  varchar(100),
    order_price   decimal
);

create table items
(
    id_item    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name  varchar(100) NOT NULL UNIQUE,
    item_price real         NOT NULL
);

create table orders_items
(
    id_order int REFERENCES orders (id_order),
    id_item  int REFERENCES items (id_item) on DELETE CASCADE
);
